### ISSUE TITLE
Misspelling of excerpt in icon name

### ISSUE THREAD

**Issue by davidlaietta** [WordPress/dashicons#189]
The excerpt view icon is named "dashicons-exerpt-view". I'm not sure how much it'd affect existing usage of dashicons to update it to the proper spelling of "dashicons-excerpt-view".

http://www.dictionary.com/browse/excerpt

**Comment by ryelle** [comment]
Looks like this was fixed in core [2 years ago](https://core.trac.wordpress.org/ticket/30832)! It was probably brought back in the switch to automated font/css generation. I think the SVG can be safely renamed.

**Comment by field2** [comment]
The name of the svg file was fixed.

**Comment by ktmn** [comment]
It's still not correct. 
https://developer.wordpress.org/resource/dashicons/#exerpt-view
I tried to use that icon in Gutenberg, but they use the `excerpt-view` name so it didn't show up.

https://github.com/WordPress/gutenberg/blob/a3776ed793a46204d2df6ebcf72c96c72d053ddf/components/dashicon/index.js#L432

Not sure which repo to make the issue, I guess here.
